import { Inter } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "./ContextApi";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>
          Quiz-app
        </title>
      </head>

      <body className={inter.className}>
        <ContextProvider>
          <Toaster position="top-center" />
          <main>{children}</main>
        </ContextProvider>
      </body>
    </html>
  );
}
