import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { ContextProvider } from "./ContextApi";
import { Toaster } from "react-hot-toast";
=======
>>>>>>> 0d1666f6efcd99b6a0679bfcd95c9c9d21fe0a72

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <head>
        <title>
          Quiz-app
        </title>
      </head>

      <body className={inter.className}>
        <ContextProvider>
          <Toaster position="top-center" />
          <main>{children}</main>
        </ContextProvider>
      </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 0d1666f6efcd99b6a0679bfcd95c9c9d21fe0a72
    </html>
  );
}
